version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  inventory.api:
    build:
      context: .
      dockerfile: Kinetic.Inventory.API/Dockerfile
    container_name: kinetic_inventory_api
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=user
      - RabbitMQ__Password=password

  notification.service:
    build:
      context: .
      dockerfile: Kinetic.Notification.Service/Dockerfile
    container_name: kinetic_notification_service
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=user
      - RabbitMQ__Password=password